name: Branch Management

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'release/**'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate branch naming
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          if [[ ! "$BRANCH_NAME" =~ ^(main|develop|feature/|release/|hotfix/) ]]; then
            echo "Invalid branch name: $BRANCH_NAME"
            echo "Branch names must follow pattern: main, develop, feature/*, release/*, hotfix/*"
            exit 1
          fi

      - name: Check branch is up to date
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin develop
          BEHIND_BY=$(git rev-list --count HEAD..origin/develop)
          if [ $BEHIND_BY -gt 0 ]; then
            echo "Branch is behind develop by $BEHIND_BY commits. Please rebase."
            exit 1
          fi

  protect:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Protect main branch
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: ['validate']
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1
              },
              restrictions: null
            }); 